version: "3.9"

services:
  apollo-back-server:
    container_name: apollo-back-server
    build:
      context: ./
    ports:
      - "${APOLLO_PORT}:${APOLLO_PORT}"
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tvshelf
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
